### ISSUE TITLE
Duplicate this to match opensearch.xml?

### ISSUE THREAD

**Issue by eklem** [fergiemcdowall/search-index-matcher#1]
Yes, I won't let it go =)
Could we have another matcher called `opensearchsuggests` and have it [comply to this setup explained in the cookbook](https://github.com/eklem/search-index-cookbook/blob/master/doc/topics/browser-search-box.md#what-you-want-it-to-return)?

**Comment by eklem** [comment]
Or add 

```
var options = {
  type: 'opensearch'  // The type of autosuggest returned- can be `simple`, `ID`, `count` or `opensearch`
}
```

**Comment by fergiemcdowall** [comment]
Yes- I like the idea of a swappable module

**Comment by eklem** [comment]
Or addable?

**Comment by eklem** [comment]
New module (forked matcher): https://github.com/eklem/search-index-opensearchsuggester
